AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway Template
Parameters:
  CognitoUserPoolClientId:
      Description: Cognito User Pool Client ID
      Type: String
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Type: String
Resources:
  ######################################## 
  # API Gateway
  ######################################## 
  # API Gateway API Endpoint
  ApiGatwayEndpoint:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api-gw"
      ProtocolType: HTTP
 
  # API Gateway Route
  ApiGwRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatwayEndpoint
      RouteKey: "GET /hello"
      AuthorizationType: NONE
      Target: !Join 
        - /
        - - integrations
          - !Ref ApiGwIntegration
 
  # API Gateway Integration
  ApiGwIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGatwayEndpoint
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'
      IntegrationUri: "http://mockbin.org/request"
 
  # API Gateway Authorizer
  ApiGwAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref ApiGatwayEndpoint
      Name: !Sub "${AWS::StackName}-ApiGwAuthorizer"
      AuthorizerType: JWT
      IdentitySource: 
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - !Ref CognitoUserPoolClientId
        Issuer: !Join 
          - ''
          - - "https://cognito-idp."
            - !Ref AWS::Region
            - ".amazonaws.com/"
            - !Ref CognitoUserPoolId
Outputs:
  oApiGatwayEndpointUrl:
    Description: The endpoint URL of the created API Gateway
    Value: !Sub "https://${ApiGatwayEndpoint}.execute-api.${AWS::Region}.amazonaws.com"
