AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Template
Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"

  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId: !Ref CognitoUserPool

Outputs:
  oCognitoUserPoolId:
    Description: Cognito user pool id
    Value: !Ref CognitoUserPool
  oCognitoUserPoolClientId:
    Description: Cognito user pool client id
    Value: !Ref CognitoUserPoolClient
