AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation example for sharing Stack information
Parameters:
  S3BucketRegion:
    Description: CF Template S3 Bucket Region
    Type: String
    Default: 'ap-southeast-2'
  S3TemplateBucketName:
    Description: CF Template S3 Bucket
    Type: String
    Default: 'overwrite-me'
  S3TemplateKeyPrefix:
    Description: CF Template S3 Bucket
    Type: String
    Default: ''
  PrereqStackName:
    Description: Prerequisite Stack Name
    Type: String
Resources:
  # Creation of API Gateway Stack
  ApiGwStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3BucketRegion}.${AWS::URLSuffix}/${S3KeyPrefix}templates/cloudformation/modules/api_gw_template.yaml'
          - S3BucketRegion: !Ref S3BucketRegion
            S3Bucket: !Ref S3TemplateBucketName
            S3KeyPrefix: !Ref S3TemplateKeyPrefix
      Parameters:
        PrereqStackName: !Ref PrereqStackName
Outputs:
  oApiGatwayEndpointUrl:
    Description: The endpoint URL of the created API Gateway
    Value: !GetAtt 'ApiGwStack.Outputs.oApiGatwayEndpointUrl'
    Export:
      Name: !Sub "${AWS::StackName}-api-gw-endpoint-url"
