AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation example for sharing Stack information
Parameters:
  S3BucketRegion:
    Description: CF Template S3 Bucket Region
    Type: String
    Default: 'ap-southeast-2'
  S3TemplateBucketName:
    Description: CF Template S3 Bucket
    Type: String
    Default: 'overwrite-me'
  S3TemplateKeyPrefix:
    Description: CF Template S3 Bucket
    Type: String
    Default: ''
Resources:
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3BucketRegion}.${AWS::URLSuffix}/${S3KeyPrefix}templates/cloudformation/modules/cognito_template.yaml'
          - S3BucketRegion: !Ref S3BucketRegion
            S3Bucket: !Ref S3TemplateBucketName
            S3KeyPrefix: !Ref S3TemplateKeyPrefix
      Parameters:
        S3BucketRegion: !Ref S3BucketRegion
        S3TemplateBucketName: !Ref S3TemplateBucketName
        S3TemplateKeyPrefix: !Ref S3TemplateKeyPrefix
  CognitoUserPoolClientId:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3BucketRegion}.${AWS::URLSuffix}/${S3KeyPrefix}templates/cloudformation/modules/ssm_template.yaml'
          - S3BucketRegion: !Ref S3BucketRegion
            S3Bucket: !Ref S3TemplateBucketName
            S3KeyPrefix: !Ref S3TemplateKeyPrefix
      Parameters:
        ParameterName: !Sub "/${AWS::StackName}/Cognito/UserPoolClientId"
        ParameterValue: !GetAtt 'CognitoStack.Outputs.oCognitoUserPoolClientId'
Outputs:
  oPrereqStackName:
    Description: Prereq Stack Name
    Value: !Ref AWS::StackName
  oCognitoUserPoolId:
    Description: Cognito User Pool Id
    Value: !GetAtt 'CognitoStack.Outputs.oCognitoUserPoolId'
    Export:
      Name: !Sub "${AWS::StackName}-cognito-user-pool-id"
  oCognitoUserPoolClientId:
    Description: Cognito User Pool Client Id
    Value: !GetAtt 'CognitoStack.Outputs.oCognitoUserPoolClientId'
    Export:
      Name: !Sub "${AWS::StackName}-cognito-user-pool-client-id"
