AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation example for sharing Stack information using git submodules
Parameters:
  Ec2SGOutboundCIDR1:
    Description: IP CIDR
    Type: String
    Default: '0.0.0.0/0'
  Ec2SGInboundCIDR1:
    Description: IP CIDR
    Type: String
  Ec2SGInboundCIDR2:
    Description: IP CIDR
    Type: String
Resources:
######################################## 
# EC2 Security Group
######################################## 
# Security Group
  EC2SecurityGroup:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W2
            reason: "This is a public facing resource and ingress from the internet should be permitted."
          - id: W9
            reason: "This is a public facing resource and ingress from the internet should be permitted."
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group managed by Security

  # Security Group Ingress Rules
  EC2SecurityGroupIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress Rule 1
      CidrIp: !Ref Ec2SGInboundCIDR1
      FromPort: 443
      GroupId:
        Fn::GetAtt:
          - EC2SecurityGroup
          - GroupId
      IpProtocol: tcp
      ToPort: 443

  EC2SecurityGroupIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress Rule 2
      CidrIp: !Ref Ec2SGInboundCIDR2
      FromPort: 443
      GroupId:
        Fn::GetAtt:
          - EC2SecurityGroup
          - GroupId
      IpProtocol: tcp
      ToPort: 443


  # Security Group Egress Rules
  EC2SecurityGroupEgress1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Egress Rule 1
      CidrIp: !Ref Ec2SGOutboundCIDR1
      FromPort: 443
      GroupId:
        Fn::GetAtt:
          - EC2SecurityGroup
          - GroupId
      IpProtocol: tcp
      ToPort: 443
Outputs:
  oSecurityGroupIds:
    Description: Security Group Ids
    Value: !Join
      - ','
      - - !GetAtt
            - EC2SecurityGroup
            - GroupId
  oSecurityGroup1Id:
    Description: Security Group Id
    Value:
      Fn::GetAtt:
        - EC2SecurityGroup
        - GroupId
