AWSTemplateFormatVersion: '2010-09-09'
Description: Sharing CloudFormation Stack information example
Parameters:
  S3BucketRegion:
    Description: CF Template S3 Bucket Region
    Type: String
    Default: 'ap-southeast-2'
  S3TemplateBucketName:
    Description: CF Template S3 Bucket
    Type: String
    Default: 'overwrite-me'
  S3TemplateKeyPrefix:
    Description: CF Template S3 Bucket
    Type: String
    Default: ''
Resources:
  # Create Prerequisite Stack for the main stack
  PrereqStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3BucketRegion}.${AWS::URLSuffix}/${S3KeyPrefix}templates/cloudformation/prereq-sharing-cf-info.yaml'
          - S3BucketRegion: !Ref S3BucketRegion
            S3Bucket: !Ref S3TemplateBucketName
            S3KeyPrefix: !Ref S3TemplateKeyPrefix
      Parameters:
        S3BucketRegion: !Ref S3BucketRegion
        S3TemplateBucketName: !Ref S3TemplateBucketName
        S3TemplateKeyPrefix: !Ref S3TemplateKeyPrefix

  # Create main Stack to consume the resources
  # from the prerequisite stack
  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3BucketRegion}.${AWS::URLSuffix}/${S3KeyPrefix}templates/cloudformation/main-sharing-cf-info.yaml'
          - S3BucketRegion: !Ref S3BucketRegion
            S3Bucket: !Ref S3TemplateBucketName
            S3KeyPrefix: !Ref S3TemplateKeyPrefix
      Parameters:
        PrereqStackName: !GetAtt 'PrereqStack.Outputs.oPrereqStackName'
        S3BucketRegion: !Ref S3BucketRegion
        S3TemplateBucketName: !Ref S3TemplateBucketName
        S3TemplateKeyPrefix: !Ref S3TemplateKeyPrefix

Outputs:
  oApiGatwayEndpointUrl:
    Description: The endpoint URL of the created API GW Gateway
    Value: !GetAtt 'MainStack.Outputs.oApiGatwayEndpointUrl'
  oCognitoUserPoolId:
    Description: Cognito User Pool Id
    Value: !GetAtt 'PrereqStack.Outputs.oCognitoUserPoolId'
  oCognitoUserPoolClientId:
    Description: Cognito User Pool Client Id
    Value: !GetAtt 'PrereqStack.Outputs.oCognitoUserPoolClientId'
